### PR TITLE
Filenames should use underscores instead of hyphens

### PR DESCRIPTION
**Pull request by paulcalabro**
This fixes the following error when importing:  *SyntaxError: invalid syntax.*

According to http://docs.python.org/reference/lexical_analysis.html#identifiers, identifiers must start with a lowercase/uppercase letter or an underscore and contain lowercase/uppercase letters, numbers or an underscore. Package names are identifiers, so they are bound to the same rules.

More info here: http://stackoverflow.com/questions/9064324/why-do-hyphens-in-module-names-generate-syntax-error

Just to be safe, I've searched for any old references and found none:

   ```
    > egrep "import.*$" -ohr  * | sort -u

    import ConfigParser
    import EdgeGridAuth
    import EdgeGridConfig
    import EdgeGridHttpCaller
    import USER_SITE
    import argparse
    import base64
    import call
    import call, check_output
    import contextlib
    import expanduser
    import gmtime, strftime
    import hashlib
    import hmac
    import httplib as http_client
    import json
    import log
    import logging
    import optparse
    import os
    import parse
    import pkg_resources
    import platform
    import randint
    import re
    import requests, logging, json
    import requests, logging, json, random, sys, re
    import requests, logging, json, sys
    import setup, find_packages
    import setuptools
    import shutil
    import subprocess
    import sys
    import sys, os
    import tempfile
    import textwrap
    import time
    import urljoin
    import urljoin, urlparse
    import urllib
    import urlopen
    import urlparse as parse
    import use_setuptools
    import uuid
    import zipfile
    imported = set(sys.modules).intersection(rep_modules)
    imported pkg_resources if present (see
   ```

### CODE REVIEW

**Comment by maglietti** [comment]
Hi Paul,

I'd like to have Kirsten take a look at this before merging it in. She is on vacation right now and should pick up the assignment when she returns after the Thanksgiving Holiday. 

Thanks again for all of your help!

-- Michael

**Comment by paulcalabro** [comment]
That sounds good! I'll check back then. Happy holidays!

**Comment by synedra** [comment]
Can you describe exactly which files you're having trouble with?

Thanks,
Kirsten

**Comment by paulcalabro** [comment]
Hi Kristen,

Sure thing. Importing the **network-lists.py** module caused the following error:

```SyntaxError: invalid syntax```

Switching to **network_lists.py** resolved the issue.
It seems to occur for other files with a hyphen in the name as well:

```
Python 2.7.6 (default, Nov 19 2015, 16:24:32)
....
>>> import billing-usage
  File "<stdin>", line 1
    import billing-usage
                  ^
```

Please let me know if you need more details.

Best,
Paul

**Comment by paulcalabro** [comment]
Hey! Just checking in. Any updates on this? :-)

**Comment by synedra** [comment]
I can fix them, but it's a little worrying because the scripts are named after the APIs they represent.  I'll merge it for now.

**Comment by paulcalabro** [comment]
Thanks Kirsten!

**Pull request merged**
